---
- name: apache（httpd）のインストール
  yum: name=httpd state=latest

- name: firewalldでHTTPを許可
  firewalld: permanent=True service=http state=enabled immediate=true

- name: サービスの起動
  service: name=httpd state=started enabled=yes
