---
- name: SELinuxの無効化
  selinux:
   policy: targeted
   state: disabled

- name: Firewalldのインストール
  yum: name=firewalld state=present

- name: Firewalldの有効化
  service: name=firewalld state=started enabled=yes
